### ISSUE TITLE
Not working under 4.1

### ISSUE THREAD

**Issue by huayra** [xcir/libvmod-awsrest#11]
Hi Shohei,

This VMOD works under 4.0.x, but when recompiled for 4.1 it doesn't work. Do you have plans to update it to support it?

**Comment by xcir** [comment]
I'll support
Please wait a little

**Comment by huayra** [comment]
Thank you.

In case you are not aware, there is a better way to do your VMOD autotools thing for 4.1, 5.0 and beyond. I would advise to check this out:

- https://github.com/varnishcache/varnish-cache/blob/4.1/varnish.m4

That applies for 4.1.4-beta1 and 5.0.0. Targetting that is probably better than try to match the VMOD descriptor format changes (the VCC file) changes that broke compatibility.

You can use this for providing 4.1 and beyond support for all your VMODs, not only this one. Example (thanks to @Dridi for making it and giving me the example) : 

- in configure.ac, you basically need this: https://github.com/Dridi/libvmod-querystring/blob/master/configure.ac#L41-L49
- in Makefile.am, you do this: https://github.com/Dridi/libvmod-querystring/blob/master/Makefile.am#L19
- in src/Makefile.am, it's simple: https://github.com/Dridi/libvmod-querystring/blob/master/src/Makefile.am#L27-L38
- for testing, easier to integrate: https://github.com/Dridi/libvmod-querystring/blob/master/src/Makefile.am#L49-L54

**Comment by Dridi** [comment]
Please note that you need Varnish 4.1.4-beta1 or later to build from git. From a dist archive, you can go down to Varnish 4.1.2, but not below because of a requirement on `vmodtool`. Let me know if there's anything you don't understand, and I will updates the crude documentation.

**Comment by xcir** [comment]
Thanks some information!
Initial support 4.1.x and 5.0.x(checked by  4.1.3, 4.1.4-beta2, 5.0.0)
---
I tried to reference the vmod-querystring.
But, can not build..(Probably my environment is bad.)
It seems that takes time to resolved, so I referred to an vmod-example.
I'm going to try a little more.
