### ISSUE TITLE
Temporary security credentials can't be used with this module

### ISSUE THREAD

**Issue by dgoodlad** [xcir/libvmod-awsrest#19]
I have found that it is currently not possible to use [temporary security credentials](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html) with this module. In #2 it was proposed that the module include support for them, but that PR was closed citing the need to keep this module simple. I understand that desire, but given some subtleties about the implementation of the signing algorithm, I think _some_ change needs to be made.

Following is an explanation of the issue, and a couple of proposed solutions. @xcir I'm interested to hear what you think is the best path for this module :smile: 

## Why can't we use temporary credentials?

When using temporary credentials, you _must_ include the `x-amz-security-token` header in requests. Additionally, the signature v4 algorithm specifies that _all_ `x-amz-*` headers be included in the signed headers list.

I would have just appended it and its value to the arguments to the `v4_generic` function like this:

```
  set bereq.http.x-amz-security-token = "[Your Security Token]";
  awsrest.v4_generic(
      "s3",
      "ap-northeast-1",
      "[Your Access Key]",
      "[Your Secret Key]",
      "host;x-amz-security-token",
      "host:" + bereq.http.host + awsrest.lf() + "x-amz-security-token:" + "bereq.http.x-amz-security-token + awsrest.lf(),
      false
  );
```

However, this _doesn't work_, because in the [signature v4 algorithm](http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html) specifies that:

> CanonicalHeaders is a list of request headers with their values. Individual header name and value pairs are separated by the newline character ("\n"). Header names must be in lowercase. **You must sort the header names alphabetically to construct the string**

The same sorting requirement is made for the SignedHeaders list:

> SignedHeaders is an **alphabetically sorted**, semicolon-separated list of lowercase request header names. The request headers in the list are the same headers that you included in the CanonicalHeaders string.

Since this module automatically appends `x-amz-content-sha256` and `x-amz-date` to the lists that have been passed in from VCL, the example above results in CanonicalHeaders being `host;x-amz-security-token;x-amz-content-sha256;x-amz-date`, which is _not_ alphabetically sorted. The same issue arises with the SignedHeaders list.

## Solutions

There are three obvious paths I think could be taken:

1. Follow the lead of what was proposed in #2; add a `token` parameter to the `v4_generic` function, and explicitly handle adding `x-amz-header` to both the signature algorithm and as a header on the request.
2. Allow the caller to _append_ headers to the list of canonical/signed headers in addition to prepending like the current behaviour.
3. Automatically sort the list of headers

Personally, I lean towards the first option. The `x-amz-security-token` header is a _core part_ of the signing and authentication system. It's also a _small change_: probably 20 or so lines of diff, after a cursory look at the module's existing code and of #2.

Option 2 feels very _hacky_, and unwieldy from a caller's point of view, but it would work.

Option 3 seems like the _most correct_ method, but would require parsing the list of headers passed in from VCL, sorting them, and re-arranging them in the list. It would open up more functionality in some services that require you pass other `x-amz` headers, but this is unlikely to be a common use case where Varnish would be in front of those kinds of services.

---

@xcir what do you think? If I opened a PR for the first option, would you consider it, despite the fact that you closed #2 before?

**Comment by xcir** [comment]
lgtm.
I'll check this weekend.

>Why closed #2?
At that time I was thinking to drop curl.(vmod_s3_generic_iam)

**Comment by xcir** [comment]
I got 400 bad request. if not set token.
I wrote a fix code, and testing now.
Merge as soon as the test is over.(and commit fixing code)

**Comment by dgoodlad** [comment]
Thanks for fixing that issue with unset token, I totally forgot to _test_ that :smile: 

:bowing_man:
