### ISSUE TITLE
Signature Mistmatch with partial query parameters

### ISSUE THREAD

**Issue by Kaelten** [xcir/libvmod-awsrest#24]
I've found a scenario where using a query parameter without an equal sign results in a signature mismatch.  

The following fails in a SignatureDoesNotMatch error: `http://127.0.0.1/13599773_10153726151001299_5411510621933484699_n.png?x`

Changing `x` to `x=` or `x=3` works fine, but `x` alone does not.  I believe this is due to S3 parsing `x` as `x=` which I can see in the CanonicalRequest.

**Comment by xcir** [comment]
ref
https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html
3-d

**Comment by xcir** [comment]
Hi, Kaelten.
I add formurl function.
Would this be okay?

Sample
```
   sub vcl_recv{
     set req.url = awsrest.formurl(std.querysort(req.url));
     awsrest.v4_generic(
       service           = "s3",
       region            = "ap-northeast-1",
       access_key        = "[Your Access Key]",
       secret_key        = "[Your Secret Key]",
       signed_headers    = "host;",
       canonical_headers = "host:" + req.http.host + awsrest.lf()
     );
   }
...
```

https://github.com/xcir/libvmod-awsrest/compare/fix/issue24

**Comment by Kaelten** [comment]
Seems reasonable to me, My only thought is that this may be needed by default since it is effectively broken without doing this.
