### ISSUE TITLE
Canonical headers when req.http.host is unset

### ISSUE THREAD

**Issue by Kaelten** [xcir/libvmod-awsrest#25]
I got hit by another odd case.

I have three backends and need to perform custom logic based on which is used.  One of the spots this has manifested is the canonical headers section.  This is because if I unset req.http.host, it'll fall back to using the backend's host when making the backend request. 

However, due to how the signing is working with this vmod it fails to be a valid signature.  Any thoughts on this one?  I'm also looking at extending Varnish separately to make more information available inside of bereq.

**Comment by xcir** [comment]
v4_generic can work in vcl_backend_fetch
see: https://github.com/xcir/libvmod-awsrest#v4_generic Example(set to bereq.*)
v4_generic gets only req.url/bereq.url internally.(client/backgroung-thread auto detect.)
ref: https://github.com/xcir/libvmod-awsrest/blob/master/src/vmod_awsrest.c#L125-L135
Other sigining parameters gets from arguments(service, region, access_key...)

**Comment by Kaelten** [comment]
The problem was I did an `unset bereq.http.host` and then when it gets put into the signing for the host header it's empty and resulted in an empty host sig.

**Comment by xcir** [comment]
Set to signed_headers="" and canonical_headers="" ,if you want not included Host by signed headears.
But, I'm not sure to success in AWS authentication.
I think Host header is necessary.
