### ISSUE TITLE
Signature Mismatch with odd URL

### ISSUE THREAD

**Issue by Kaelten** [xcir/libvmod-awsrest#28]
Got another bad URL pattern that triggers a signature mismatch.  This one is not valid, but would rather it 404 then return a 403 due to the mismatch.

Example URL: `http://127.0.0.1/13599773_10153726151001299_5411510621933484699_n.png=test`

**Comment by xcir** [comment]
This module does not care to URIencode/decode.
see: https://github.com/xcir/libvmod-awsrest#common-problems

**Comment by Kaelten** [comment]
Ah, so I could use something like this maybe? https://github.com/fastly/libvmod-urlcode

**Comment by xcir** [comment]
Maybe...
Because, many points to consider different use cases.

example.
- /Hi/how are you doing today?

urlencoded
- /Hi/how+are+you+doing+today%3F
- /Hi/how+are+you+doing+today? (? is query separator)

I don't know which is correct...
