### ISSUE TITLE
SignatureDoesNotMatch 

### ISSUE THREAD

**Issue by myhub1982** [xcir/libvmod-awsrest#3]
Using the example posted, i keep getting a signature mismatch...

"The request signature we calculated does not match the signature you provided. Check your key and signing method."

i used the aws id/secret key provided by s3 api. i can use them to reach my s3 based object using s3cmd, but not through varnish..

**Comment by GeorgePhillips** [comment]
I am having the same issue. Did you end up solving it?

**Comment by xcir** [comment]
Sorry to fix so late.
Support to AWS v4 signature.

https://github.com/xcir/libvmod-awsrest/commit/aaa14af00d11e2d00e31855365de3ad1bf48f648
